#!/bin/bash
 
# create an empty XAUTH file
XAUTH=/tmp/.docker.xauth
>> $XAUTH
 
# add XAUTH credentials and change owner and permissions of XAUTH file
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | sudo xauth -f $XAUTH nmerge -
sudo chown liang.xu $XAUTH
sudo chmod 600 $XAUTH
 
# get display ID to get TCP port number
X11PORT=`echo $DISPLAY | sed 's/^[^:]*:\([^\.]\+\).*/\1/'`
TCPPORT=`expr 6000 + $X11PORT`
 
# enable TCP porting to display
sudo ufw allow from 127.0.0.1/16 to any port $TCPPORT proto tcp
DISPLAY=`echo $DISPLAY | sed 's/^[^:]*\(.*\)/127.0.0.1\1/'`
